### PR TITLE
Improve in-process IPFS client so we can upload/download files/dirs, and run local IPFS networks for testing.

### LINKED ISSUE #303: `bacalhau get` doesn't work for devstack
Currently `bacalhau get` connects to the public IPFS network, but devstack runs its own isolated local one. We need to add a flag for setting the network somehow.

https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1656424550962629

### PR DESCRIPTION
**Pull request by Bubblyworld**
Fixes #303, see #324. Adds a bunch of support for new stuff in the in-process IPFS client:
1. you can now run in `ModeLocal` to avoid using the public IPFS network for test environments
2. you can now upload and download files and directories using the client
3. `bacalhau get` now supports an optional `--ipfs-swarm-addrs` flag to connect to a specific IPFS swarm node (such as devstack)

Should now be possible to replace the IPFS shell code in devstack with this client.

### CODE REVIEW

**Comment by Bubblyworld** [comment]
It's short lived in `bacalhau get`, but we don't do uploading there - in `bacalhau devstack` the client will live as long as the devstack process is going. Basically the behaviour doesn't change.

**Comment by Bubblyworld** [comment]
Mmm, there's an argument for splitting the in-process node and client though, conflating them a little here.

**Comment by lukemarsden** [comment]
ok cool. Just FYI, I also wired up the requestor node to upload to IPFS here in the recent language frontend / python_wasm work: https://github.com/filecoin-project/bacalhau/blob/main/pkg/requestornode/requesternode.go#L130

**Comment by Bubblyworld** [comment]
Cool, noted, seems like there's still a bit of complexity to unwind... I'll have a think about the best way to do this, maybe what I should do is have an in-process node implementation for running a node locally, and a separate API client (like the httpclient we already have), maybe with some util code for getting a client that points to your local node easily.

Should just be a matter of reorganising stuff I think.

**Pull request merged**
