### PR TITLE
see if the ci has a problem with moving to a newer ipfs release

### PR DESCRIPTION
**Pull request by SvenDowideit**
for #1443 - I think this is what @lukemarsden was suggesting https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1669879737112089?thread_ts=1669877835.083799&cid=C02RLM3JHUY

### CODE REVIEW

**Comment by lukemarsden** [comment]
gah, we need a way to approve running CI on external PRs.

**Comment by lukemarsden** [comment]
also I think we probably need to bump the kubo dep in go.mod as well to test vendoring the later ipfs?

**Comment by lukemarsden** [comment]
(I don't think CI runs against an _external_ IPFS ever)

**Comment by philwinder** [comment]
Closed in favour of #1749 (to allow the CI to run).

**Pull request closed without merging**
