### PR TITLE
enable running requester and computer nodes separately

### PR DESCRIPTION
**Pull request by wdbaruni**
With this PR, each bacalhau node can be either a `compute` node, `requester` node or both (a hybrid node). 

### `serve` command changes
```
# Start a bacalhau compute node
bacalhau serve
# or
bacalhau serve --node-type compute

# Start a bacalhau requester node
bacalhau serve --node-type requester

# Start a bacalhau hybrid node that acts as both compute and requester
bacalhau serve --node-type compute --node-type requester
# or
bacalhau serve --node-type compute,requester
```

### `devstack` command changes
```
# Create a devstack cluster with a single requester node and 3 compute nodes (Default values)
bacalhau devstack 

# Create a devstack cluster with a two requester nodes and 10 compute nodes
bacalhau devstack  --requester-nodes 2 --compute-nodes 10

# Create a devstack cluster with a single hybrid (requester and compute) nodes
bacalhau devstack  --requester-nodes 0 --compute-nodes 0 --hybrid-nodes 1 
```

### API paths changes
Nodes will still have a single `publicapi.APIServer` instance with a single port, but the API paths have changed as follows:
```
# node health and core APIs are at the root. e.g.
/livez
/id
/peers
...

# requester specific APIs are under /requester e.g.
/requester/submit
/requester/list
/requester/debug

# compute specific APIs are under /compute. Currently we only have /compute/debug API the returns available capacity and active executions
```

### CODE REVIEW

**Comment by wdbaruni** [comment]
Will look into fixing swagger issue tomorrow. Might have to sync up with @enricorotundo

**Comment by wdbaruni** [comment]
@aronchick @lukemarsden let me know if you have feedback on the cli user experience, and the selection of the node type

**Comment by lukemarsden** [comment]
LGTM

**Comment by enricorotundo** [comment]
@wdbaruni Don't worry about the swagger error - fixed by https://github.com/filecoin-project/bacalhau/pull/1642/commits/529dae8c934cb348c8674d9bd5fd8d5d867bce35

**Comment by enricorotundo** [comment]
@wdbaruni QQ: How does the load balancer know how to route `/requester/*` calls to requester-nodes only?

**Comment by wdbaruni** [comment]
Thanks @enricorotundo for fixing swagger. You are the best! 

As for your question, all our managed nodes will be deployed as both requester and compute nodes. In the future, we will change the load balancer to only point to the requester only nodes. I've also updated the client so that `Submit` requests will go to `/requester/submit` instead of `/submit`

**Comment by parthbond180** [comment]
hi is there a plan to provide a similar function for the executor interface?

**Pull request merged**
